name: openai_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.18.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  envied: ^0.3.0
  envied_generator: ^0.3.0
  freezed_annotation: ^2.2.0
  http: ^0.13.5
